name: Test action
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.dove
          key: ${{ runner.os }}-dove
      - name: download latest version
        uses: vladimirovmm/dove_download_test@test
      - name: test
        run: dove -V
      - name: download 1.2.1 version
        uses: vladimirovmm/dove_download_test@test
        with:
          version: 1.2.1
      - name: test
        run: dove -V
      - name: download 1.1.4 version
        uses: vladimirovmm/dove_download_test@test
        with:
          version: 1.1.4
      - name: test
        run: dove -V
